spring:
  profiles:
    active: ${SPRING_ACTIVE_PROFILES:}
  flyway:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/djed}
    user: ${DB_USERNAME:djed}
    password: ${DB_PASSWORD:password}
    schemas: ${DB_SCHEMA:}
    locations:
      - classpath:db/store/{vendor}
      - classpath:db/store/djed
    out-of-order: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/djed}
    username: ${DB_USERNAME:djed}
    password: ${DB_PASSWORD:password}

blockfrost:
  url: ${BLOCKFROST_URL:https://cardano-mainnet.blockfrost.io/api/v0/}
  key: ${BLOCKFROST_KEY:}

store:
  cardano:
    host: ${REMOTE_NODE_URL:relays-new.cardano-mainnet.iohk.io}
    port: ${REMOTE_NODE_PORT:3001}
    protocol-magic: 764824073
    # Start from the block that minted the ref input for the contract
    sync-start-slot: ${YACI_STORE_CARDANO_SYNC_START_SLOT:152236800}
    sync-start-blockhash: ${YACI_STORE_CARDANO_SYNC_START_BLOCK_HASH:1abc3c6c75bcd004b24278260cc58c0aa55d5af707dfb46a426b36a5f60668be}
  blocks:
    epoch-calculation-interval=14400:  # 14400 = 4 hours

apiPrefix: /api/v1
